title: "Layan Albelbisi's Data Portfolio"
description: "Showcasing projects and skills in Data Analysis and Business Intelligence."
baseurl: "" # leave empty for root
theme: minima # or another theme you prefer

# Navigation
plugins:
  - jekyll-feed

# Optional: Social Links
social:
  github: "https://github.com/yourusername" # replace with your GitHub profile
  linkedin: "https://linkedin.com/in/layan-bilbeisi" # replace with your LinkedIn profile

# Markdown options
markdown: kramdown
